title: Learning Theory docs
description: Take a Hike versions
theme: just-the-docs

url: https://magnuson8.github.io/learning_theory


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
